# Generated by Django 5.0.2 on 2024-02-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='poi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('poi_price', models.CharField(max_length=200)),
            ],
        ),
    ]
