# Generated by Django 5.0.2 on 2024-02-26 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_poi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='poi',
        ),
    ]
