# Generated by Django 5.0.2 on 2024-02-27 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_delete_poi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='date',
            new_name='year_of_birth',
        ),
    ]
